php:
  preset: laravel

  risky: true

  enabled:
    - concat_with_spaces
    - alpha_ordered_imports

  disabled:
    - concat_without_spaces
    - length_ordered_imports

  finder:
    exclude:
      - modules
      - node_modules
      - storage
      - vendor

    name:
      - "*.php"

    not-name:
      - "*.blade.php"
      - ".phpstorm.meta.php"
      - "_ide_helper.php"

css: true
js: true
